# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

apply = ["defer"]

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.chezmoi]
local = "~/bin/"
apply = ["PATH"]

[plugins.cargo]
local = "~/.cargo/bin"
apply = ["PATH"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.async]
github = "mafredri/zsh-async"
apply = ["source"]

[plugins.pure]
github = "sindresorhus/pure"
apply = ["source"]

[plugins.pure-disable-git-pull]
inline = "export PURE_GIT_PULL=0"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.z]
github = "rupa/z"

[plugins.ls-after-cd]
inline = "function cd(){builtin cd $@ && ls}"

[plugins.export-editor-vim]
inline = "export EDITOR=vim"

[plugins.bindkey-e]
inline = "bindkey -e"

[plugins.dot_async]
local = "~/.config/sheldon/"
use = ["{!sync,*}.zsh"]

# syncを使いたくなったらアンコメントする
# [plugins.dot_sync]
# local = "~/.config/sheldon/"
# use = ["sync.zsh"]
# apply = ["source"]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
